### ISSUE TITLE
launcher file name typo

### ISSUE THREAD

**Issue by tsuyoshicho** [hokorobi/vim-clap-launcher#1]
https://github.com/hokorobi/vim-clap-launcher/blob/657378bf3b83c2594115b96bca2eee1749b0e8ff/doc/clap-launcher.txt#L30

code as:

https://github.com/hokorobi/vim-clap-launcher/blob/657378bf3b83c2594115b96bca2eee1749b0e8ff/autoload/clap/provider/launcher.vim#L1

need fixit 😄

**Comment by hokorobi** [comment]
Thank you 😅
